<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

namespace Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.common.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 message_type = 1;</code>
     */
    private $message_type = 0;
    /**
     * Generated from protobuf field <code>int64 message_cmd = 2;</code>
     */
    private $message_cmd = 0;
    /**
     * Generated from protobuf field <code>int32 message_len = 3;</code>
     */
    private $message_len = 0;

    public function __construct() {
        \GPBMetadata\Header::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 message_type = 1;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->message_type;
    }

    /**
     * Generated from protobuf field <code>int32 message_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkInt32($var);
        $this->message_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 message_cmd = 2;</code>
     * @return int|string
     */
    public function getMessageCmd()
    {
        return $this->message_cmd;
    }

    /**
     * Generated from protobuf field <code>int64 message_cmd = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageCmd($var)
    {
        GPBUtil::checkInt64($var);
        $this->message_cmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 message_len = 3;</code>
     * @return int
     */
    public function getMessageLen()
    {
        return $this->message_len;
    }

    /**
     * Generated from protobuf field <code>int32 message_len = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageLen($var)
    {
        GPBUtil::checkInt32($var);
        $this->message_len = $var;

        return $this;
    }

}

