<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

namespace GPBMetadata;

class Header
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a0c6865616465722e70726f746f120c70726f746f2e636f6d6d6f6e" .
            "22480a0648656164657212140a0c6d6573736167655f7479706518012001" .
            "280512130a0b6d6573736167655f636d6418022001280312130a0b6d6573" .
            "736167655f6c656e180320012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

