<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kernel.proto

namespace GPBMetadata;

class Kernel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Header::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6e0a0c6b65726e656c2e70726f746f120d70726f746f2e6d6f6e69746f" .
            "7222470a064b65726e656c12240a0668656164657218012003280b32142e" .
            "70726f746f2e636f6d6d6f6e2e48656164657212170a0f6d657373616765" .
            "5f636f6e74656e74180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

