<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kernel.proto

namespace Proto\Monitor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.monitor.Kernel</code>
 */
class Kernel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.common.Header header = 1;</code>
     */
    private $header;
    /**
     * Generated from protobuf field <code>string message_content = 2;</code>
     */
    private $message_content = '';

    public function __construct() {
        \GPBMetadata\Kernel::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .proto.common.Header header = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.common.Header header = 1;</code>
     * @param \Proto\Common\Header[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Common\Header::class);
        $this->header = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message_content = 2;</code>
     * @return string
     */
    public function getMessageContent()
    {
        return $this->message_content;
    }

    /**
     * Generated from protobuf field <code>string message_content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->message_content = $var;

        return $this;
    }

}

